### ISSUE TITLE
"Invalid resource directory name" Error

### ISSUE THREAD

**Issue by afaucogney** [usefulness/easylauncher-gradle-plugin#88] opened 2020-09-28 08:59 UTC
Hello,

  I was setting a project with multi modules to help solving https://github.com/usefulness/easylauncher-gradle-plugin/issues/77. 

  I just created a project with AS 4.1, added EasyLauncher and I get this error:
```
> Task :app:mergeDebugResources FAILED
AGPBI: {"kind":"error","text":"Invalid resource directory name","sources":[{"file":"/Users/afaucogney/AndroidStudioProjects/MyApplication/app/build/generated/easylauncher/res/debug/drawable-v24-ldpi"}],"tool":"Resource and asset merger"}
```

I tried with 3.3 and 3.5.

Here is the project https://github.com/afaucogney/multimodule-easylauncher

I will then update with multi module configuration

**Comment by mateuszkwiecinski** [comment] 2020-09-28 10:23
Huh, I thought I fixed that one :/ I'll take another look. As a temporary workaround you can move `ic_launcher_foreground.xml` to unqualified `drawable` folder

**Comment by mateuszkwiecinski** [comment] 2020-09-28 17:51
I tried to reproduce that, and I'm not able to reproduce the issue on the recent version. I forked your repository and while it indeed fails on 3.3.0 with mentioned issue, it doesn't on 3.5.0
https://github.com/mateuszkwiecinski/multimodule-easylauncher/pull/1
![image](https://user-images.githubusercontent.com/36954793/94467752-ab5a3b80-01c3-11eb-8a97-719bc920ef52.png)
I might needed to run `./gradlew :app:clean` to remove invalid resource and let newer plugin version to regenerate the icon.

**Comment by mateuszkwiecinski** [comment] 2020-10-05 19:20
Fixed by https://github.com/usefulness/easylauncher-gradle-plugin/pull/81

**Closed by mateuszkwiecinski** 2020-10-05 19:20 UTC
Labels: bug

**Comment by afaucogney** [comment] 2020-11-05 14:23
@mateuszkwiecinski sory for being late. I just updated my project, with the latest version, but it doesn't worked as expected. Could you please have a look ?

So I added the icon_name, bit the ribon is not applied ! Did I missed something ?

https://github.com/afaucogney/multimodule-easylauncher

**Comment by mateuszkwiecinski** [comment] 2020-11-05 16:54
Hello again @afaucogney 👋 
You applied the plugin to your `app` module instead of the library module you have the icon declared with. If you apply the plugin to your `uikit` module the ribbon will show up:
![image](https://user-images.githubusercontent.com/36954793/98271093-db011e00-1f8f-11eb-9c69-7f9b1865d882.png)

**Comment by afaucogney** [comment] 2020-11-05 17:58
Thanks for helping @mateuszkwiecinski, but unfortunately, the flavors are bot defined in the lib.

Imagine the projet for a multi-brand app

app
  buildType debug / release
  flavor 
    env dev, staging, prod
    push dev, prod
    brand brand1, brand2

  implementationBrand1(:uikit-brand1)
  implementationBrand2(:uikit-brand2)

modules brand1, and brand2 own the same launcher icons names.

But this at the app level, that I want to apply ribon depending on configuration. Then this is the module selection that will select the good icon.

Come back to me if this is not 100% clear. Then I can update my project with a similar config. But before, you should tell me this is more or less feasable.

Greetings.

**Comment by mateuszkwiecinski** [comment] 2020-11-09 08:33
I'm sorry. but I don't fully understand you mesage, I didn't get neither the dependencies nor what you're trying to achieve, what is the expected output. From my understanding your setup heavily relies on an assumption that all feature modules declare the same icon resource name. It is not a reliable assumption for the plugin 🤔 
The plugin cannot modify resources declared in other modules, so basically to make the plugin work you have to keep `android:icon` in the same module as the icon resource and apply the plugin in corresponding `build.gradle`

**Comment by afaucogney** [comment] 2020-11-09 15:01
> . From my understanding your setup heavily relies on an assumption that all feature modules declare the same icon resource name. It is not a reliable assumption for the plugin 
Yes

Let's give you a more concrete example:
Imagine I'm building an app for the Volkwagen Group. They want an app for Audi, VW and Skoda. Same behaviour of the app, but different endpoint. We want to be able to build 3 different branded apps, with 2 buildType : Release/Debug, with 2 web-service environment flavour : Prod / Staging. This does means 3 * 2 * 2 = 12 different app configuration, but with only 3 different icons (one by brand)

Every brand ui resources (color, launcher icon ... ) is setup in a specific android module named `ui-kit-$brandName`, that own ofcourse the ic_launcher icon resource.  

Every ui-kit module does only have 2 buildType (debug, release), no Flavours

From the app, I want to be able to add a ribbon if the buildType is debug, but the icon retrieved from the selected ui-kit must be automatically retrieved from the brand favour selection.

When you sync Gradle, only a single module is available. However it is is the module. Again the flavor I want to use to setup easylauncher are in the app.

Is this more clear ?

**Comment by afaucogney** [comment] 2020-11-13 16:44
@mateuszkwiecinski Did you had the chance to have a look on my topic ?

**Comment by mateuszkwiecinski** [comment] 2020-11-28 17:14
Hey @afaucogney 👋  Sorry for the long waiting. 
As per my understanding the plugin can't support your case as it don't have access to resources owned by a different module than the plugin was applied to. 
If you want you can create a sample repository that resembles your case and I'll try to figure something out :)
