### ISSUE TITLE
Duplicate resources Error

### ISSUE THREAD

**Issue by HashirLabs** [usefulness/easylauncher-gradle-plugin#408] opened 2023-01-18 13:15 UTC
I am getting Duplicate resources error on app build. I tried with clean build and deleted build folder as well with no luck. Here is the details of library versions i am using

Android Studio : **Android Studio Electric Eel | 2022.1.1**
Gradle: **distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip**
Android Gradle Plugin: **7.4.0 (https://maven.google.com/web/index.html?q=gradle#com.android.application:com.android.application.gradle.plugin:7.4.0)**
Java Version: **11 (Android JRE)**

```
> Task :app:mergeDebugResources FAILED
Execution failed for task ':app:mergeDebugResources'.
Caused by: [mipmap-hdpi-v4/ic_launcher] <project_path>\app\src\main\res\mipmap-hdpi\ic_launcher.png	[mipmap-hdpi-v4/ic_launcher] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-hdpi\ic_launcher.png: Error: Duplicate resources
[mipmap-hdpi-v4/ic_launcher_foreground] <project_path>\app\src\main\res\mipmap-hdpi\ic_launcher_foreground.png	[mipmap-hdpi-v4/ic_launcher_foreground] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-hdpi\ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-hdpi-v4/ic_launcher_round] <project_path>\app\src\main\res\mipmap-hdpi\ic_launcher_round.png	[mipmap-hdpi-v4/ic_launcher_round] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-hdpi\ic_launcher_round.png: Error: Duplicate resources
[mipmap-mdpi-v4/ic_launcher] <project_path>\app\src\main\res\mipmap-mdpi\ic_launcher.png	[mipmap-mdpi-v4/ic_launcher] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-mdpi\ic_launcher.png: Error: Duplicate resources
[mipmap-mdpi-v4/ic_launcher_foreground] <project_path>\app\src\main\res\mipmap-mdpi\ic_launcher_foreground.png	[mipmap-mdpi-v4/ic_launcher_foreground] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-mdpi\ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-mdpi-v4/ic_launcher_round] <project_path>\app\src\main\res\mipmap-mdpi\ic_launcher_round.png	[mipmap-mdpi-v4/ic_launcher_round] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-mdpi\ic_launcher_round.png: Error: Duplicate resources
[mipmap-xhdpi-v4/ic_launcher] <project_path>\app\src\main\res\mipmap-xhdpi\ic_launcher.png	[mipmap-xhdpi-v4/ic_launcher] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xhdpi\ic_launcher.png: Error: Duplicate resources
[mipmap-xhdpi-v4/ic_launcher_foreground] <project_path>\app\src\main\res\mipmap-xhdpi\ic_launcher_foreground.png	[mipmap-xhdpi-v4/ic_launcher_foreground] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xhdpi\ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-xhdpi-v4/ic_launcher_round] <project_path>\app\src\main\res\mipmap-xhdpi\ic_launcher_round.png	[mipmap-xhdpi-v4/ic_launcher_round] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xhdpi\ic_launcher_round.png: Error: Duplicate resources
[mipmap-xxhdpi-v4/ic_launcher] <project_path>\app\src\main\res\mipmap-xxhdpi\ic_launcher.png	[mipmap-xxhdpi-v4/ic_launcher] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xxhdpi\ic_launcher.png: Error: Duplicate resources
[mipmap-xxhdpi-v4/ic_launcher_foreground] <project_path>\app\src\main\res\mipmap-xxhdpi\ic_launcher_foreground.png	[mipmap-xxhdpi-v4/ic_launcher_foreground] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xxhdpi\ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-xxhdpi-v4/ic_launcher_round] <project_path>\app\src\main\res\mipmap-xxhdpi\ic_launcher_round.png	[mipmap-xxhdpi-v4/ic_launcher_round] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xxhdpi\ic_launcher_round.png: Error: Duplicate resources
[mipmap-xxxhdpi-v4/ic_launcher] <project_path>\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png	[mipmap-xxxhdpi-v4/ic_launcher] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xxxhdpi\ic_launcher.png: Error: Duplicate resources
[mipmap-xxxhdpi-v4/ic_launcher_foreground] <project_path>\app\src\main\res\mipmap-xxxhdpi\ic_launcher_foreground.png	[mipmap-xxxhdpi-v4/ic_launcher_foreground] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xxxhdpi\ic_launcher_foreground.png: Error: Duplicate resources
[mipmap-xxxhdpi-v4/ic_launcher_round] <project_path>\app\src\main\res\mipmap-xxxhdpi\ic_launcher_round.png	[mipmap-xxxhdpi-v4/ic_launcher_round] <project_path>\app\build\generated\res\easylauncherDebug\mipmap-xxxhdpi\ic_launcher_round.png: Error: Duplicate resources
	at com.android.ide.common.resources.DataSet.checkItems(DataSet.java:512)
	at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:273)
	at com.android.ide.common.resources.DataSet.loadFromFiles(DataSet.java:243)
	at com.android.build.gradle.tasks.MergeResources$doFullTaskAction$1$1$1.invoke(MergeResources.kt:244)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:51)
	at com.android.build.gradle.tasks.MergeResources.doFullTaskAction(MergeResources.kt:238)
```

Note that in above exception, i have replaced actual project path on my D drive with **<project_path>** for brevity. I had been waiting for stable AGP 7.4.0 and Android Studio EE release to use with the latest version of this lib (6.1.0), but no luck

Please advise

**Comment by mateuszkwiecinski** [comment] 2023-01-18 13:47
Yeah, unfortunately, 7.4.0 was released with a known bug which affects versions 7.3 and 7.4.
7.3 fails silently, 7.4 throws with an error you are experiencing. 

The bug was reported in 7.4's early alpha, but still made into "stable" release https://issuetracker.google.com/issues/244063664
7.4.0 also introduces another reggression, also reported early: https://issuetracker.google.com/issues/261329823. 

In your particular case, adding a `android.disableResourceValidation=true` to your `gradle.properties` could help, although I don't fully understand the workaround, so I don't know if it doesn't introduce any side effects. This tip comes from one of [googlers](https://issuetracker.google.com/issues/244063664#comment5).

If you're looking for more resources, you can visit:
1. https://github.com/usefulness/easylauncher-gradle-plugin/issues/349
2. https://github.com/usefulness/easylauncher-gradle-plugin/issues/382
3. https://github.com/usefulness/easylauncher-gradle-plugin/issues/387

to learn more on how broken AGP became these days :/ 

8.0 alphas seem to merge resources correctly, and according to issuetracker they plan to release 7.4.1 which suppose to fix these issues 🤷 
There is nothing I can do on the plugin side to work around these issues.

**Comment by rizwan-dev** [comment] 2023-02-07 14:31
Yes, I am also facing issue on AGP 7.4.1 and easyLauncher version 6.1.0. On adding to android.disableResourceValidation=true is not showing the error, but label is not getting added to icon with this.

**Comment by peerless2012** [comment] 2023-02-08 11:48
Have the same issue at 7.4.0.

**Comment by HashirLabs** [comment] 2023-03-02 07:44
I upgraded to latest AGP 7.4.2 released

Unfortunately the fix still didn't make it to the stable version and the the problem still persists.

**Comment by RahulSDeshpande** [comment] 2023-03-22 08:37
Folks, is there any update on this issue?

**Closed** 2023-04-17 07:30 UTC

**Comment by RahulSDeshpande** [comment] 2023-05-15 10:22
@HashirLabs
Correct, the issue is no more for `AGP 8.0`.

🥳

**Comment by cosminstefanxp** [comment] 2023-07-18 07:24
For what it's worth, while it works fine for me with AGP 8+ and `minSdk` 26, if I move the `minSdk` to 23, I still get the issue:
<img width="716" alt="image" src="https://github.com/usefulness/easylauncher-gradle-plugin/assets/1536594/0bb765a6-e0aa-4781-8dd6-e65809836c54">

I believe it has to do to the fact that `minSdk` 23 requires both a `mipmap-anydpy` (without `adaptive-icon`) and a `mipmap-anydpi-26` (with `adaptive-icon`), right?

**Comment by mateuszkwiecinski** [comment] 2023-07-18 11:27
@cosminstefanxp I bet a clean build will solve your issue 🤞 Please do file a separate issue with a repro project otherwise (to not ping everyone in the thread here)

**Comment by cosminstefanxp** [comment] 2023-07-18 13:56
Hello. No, unfortunately clean didn't solve it (tried fully cleaning - gradle, build folders etc.). I'll see if I'll find a bit of time the next few days for a demo project. But replications steps are pretty much: change minSDK to 23.
