### ISSUE TITLE
Basic usage doesn't work

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [usefulness/easylauncher-gradle-plugin#58] opened 2020-09-03 10:15 UTC
Just applying the plugin and installing the debug variant, it doesn't show the debug label.

I think this can be related to issue #57

**Comment by mateuszkwiecinski** [comment] 2020-09-03 12:36
Would you be able to provide more infor about your local setup?
1. device API level which doesn't show the ribbon? 
2. path to the launcher icon resource file for the above api level?

**Comment by JavierSegoviaCordoba** [comment] 2020-09-03 13:06
I am just using:

plugins {
  id("com.starter.easylauncher") version "3.2.0"
}

I tried in another project without Kotlin DSL and it is working, but I don't know if its related.

On the other hand, it is working but badges are cut

![image](https://user-images.githubusercontent.com/7463564/92118598-f8323880-edf6-11ea-90f0-eeece64a4aaf.png)

**Comment by mateuszkwiecinski** [comment] 2020-09-03 14:07
>I tried in another project without Kotlin DSL and it is working, but I don't know if its related.

Starting from `3.2.0` there shouldn't be any differences between Kotlin DSL and Groovy scripts usage. 
My suspicion is that your project has similar structure as on the image below and keeps one of the launcher icons under `-anydpi-v26` folder.
<img width="365" alt="Screenshot 2020-09-03 at 15 56 23" src="https://user-images.githubusercontent.com/36954793/92124594-40a12480-edfe-11ea-9d73-58811ed2e873.png">
I confirmed the plugin doesn't behave correctly then and it should be fixed by https://github.com/usefulness/easylauncher-gradle-plugin/pull/61. Could you confirm that's also the applicable in your case? 

>On the other hand, it is working but badges are cut

It looks like a Samsung's TouchWiz (or other launcher) trying to adapte a non-adaptive icon. Could you confirm the other project properly declares [Adaptive Icon](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive) resource?

**Comment by mateuszkwiecinski** [comment] 2020-09-03 14:36
I just released version `3.2.1` which hopefully solves the original issue 🤞 
```
plugins {
    id("com.starter.easylauncher") version "3.2.1"
}
```
If it doesn't, I would appreciate if you could try to reproduce it on a [sample project](https://github.com/mateuszkwiecinski/easylauncher_sample/blob/master/app/build.gradle.kts#L3)

Thanks for trying out the library and reporting issues!

**Comment by JavierSegoviaCordoba** [comment] 2020-09-04 08:22
You are welcome :D

It is not working for me, you can check it in [this branch](https://github.com/JavierSegoviaCordoba/Paginate/tree/easylauncher)

In my private project appear nothing, but I can public it :/

**Comment by mateuszkwiecinski** [comment] 2020-09-04 09:34
> It is not working for me, you can check it in this branch

Actually, it works as expected. The linked project doesn't use adaptive icons thus your legacy launcher icon gets wrapped in an additional padding to make it look consistent with other apps. 
![image](https://user-images.githubusercontent.com/36954793/92224733-81527980-eea2-11ea-8558-75240e7edffd.png)

Your app should start using adaptive icon, as described in:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Closed** 2020-09-22 19:20 UTC

**Comment by JavierSegoviaCordoba** [comment] 2021-01-11 14:17
Is there a way to debug why badges can't appear?

**Comment by mateuszkwiecinski** [comment] 2021-01-11 15:33
I think the easiest way of knowing why the icon doesn't match expectations is to look at generated files under `build/generated/easylauncher` which should point at what has been generated and for which build variants. Clearing generated folder can also help to make sure it contains changes only from the last task invocation.
I also added some logs visible when running gradle command with `--info` flag (i.e. `./gradlew easylauncherDebug --info`), but I don't know how useful they are. 

If you want you create sample project under [/sample](https://github.com/usefulness/easylauncher-gradle-plugin/tree/master/sample) directory with a desired configuration and then you should be able to attach a debugger to the plugin and investigate it on your own.
