### ISSUE TITLE
Build fails with map(provider(java.util.Set)) not supported after upgrading to AGP 7.4.0-rc01 and 6.1.0

### ISSUE THREAD

**Issue by leinardi** [usefulness/easylauncher-gradle-plugin#387] opened 2022-12-06 09:53 UTC
After upgrading the Android Gradle Plugin from `7.4.0-beta05` to `7.4.0-rc01` the build fails with the error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mapDebugSourceSetPaths'.
> Querying the mapped value of map(provider(java.util.Set)) before task ':app:easylauncherDebug' has completed is not supported
```

Easy launcher version 6.1.0 (version 6.0.0 seems to not be affected).
Gradle 7.5.1 (tested also with 7.6.)
Gradle command:  `./gradlew assembleDebug assembleDebugAndroidTest`

**Comment by mateuszkwiecinski** [comment] 2022-12-08 08:14
Hey 👋 Thanks for reporting the issue. I'm unable to confirm that on my end right now, but it seems like that's a known bug of AGP which became extremely unstable recently 🤷‍♂️ https://issuetracker.google.com/issues/261329823

As far as I saw, there will be another RC of 7.4.0, so hopefully it will be fixed on their side.

**Comment by casperbang** [comment] 2022-12-13 07:04
I can confirm hitting this issue as well. Better to stay on 7.4.0-beta05 and hope 7.4.0-rc02 remedies the situation.

**Comment by luanbarbosa-sanoma** [comment] 2022-12-14 13:32
Same for me. With AGP `8.0.0-alpha09` version `6.1.0` fails but `6.0.0` works fine.

**Comment by mateuszkwiecinski** [comment] 2022-12-22 07:43
I'll share a small update:
According to the [issue](https://issuetracker.google.com/issues/261329823) linked above, the fix will be available in the following versions: 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/36954793/209081518-f9f021e3-4304-4fd9-a54e-3beb778f0116.png">
I did a [smoke test](https://github.com/usefulness/easylauncher-gradle-plugin/pull/392) and latest `8.0.0-alpha10` seems to be working fine again, 7.4.0-rc2 is still affected. As far as I understand, the bug will land in a "stable" release, and we'll have to wait for a patch release 🤷

**Comment by ivannarino** [comment] 2023-01-16 17:38
I can confirm the bug still happens in 7.4.0 release with 6.1.0

**Comment by mateuszkwiecinski** [comment] 2023-02-01 22:14
It seems like the issue has been fixed in AGP `7.4.1`, or at least I'm not able to reproduce it anymore 👀 

I'm going to close this issue, but I'll leave a reminder that:`7.4.1` still has this bug: https://issuetracker.google.com/issues/244063664 and requires a [workaround](https://issuetracker.google.com/issues/244063664#comment5) for it, but other than that it seems to work just fine 👀

**Closed by mateuszkwiecinski** 2023-02-01 22:14 UTC

**Comment by leinardi** [comment] 2023-02-02 14:34
I can confirm that version 6.1.0 and AGP 7.4.1 works fine now, but `android.disableResourceValidation=true` is still required.
