### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by mahipalsingh-syt** [usefulness/easylauncher-gradle-plugin#310] opened 2022-05-20 12:37 UTC
Task :app:easylauncherStageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:easylauncherStageDebug'.
> java.lang.reflect.InvocationTargetException

**Comment by mateuszkwiecinski** [comment] 2022-05-20 12:58
Can you share the full exception? Either sharing a full build scan `--scan` or just the `--stacktrace`

**Comment by mahipalsingh-syt** [comment] 2022-05-20 13:01
@mateuszkwiecinski  here the full Exception


`#!/bin/bash -eo pipefail
cd android
sudo chmod +x ./gradlew
(sdkmanager --update && yes | sdkmanager --licenses) && echo accepted || echo ACCEPTED
./gradlew clean
cd ..
npx jetify
cd android && ./gradlew app:assemblestage

[=======================================] 100% Unzipping... emulator/qemu/linux-
All SDK package licenses accepted.======] 100% Computing updates...             

ACCEPTED
Downloading https://services.gradle.org/distributions/gradle-7.3-all.zip
...............10%...............20%...............30%...............40%...............50%...............60%................70%...............80%...............90%...............100%

Welcome to Gradle 7.3!

Here are the highlights of this release:
 - Easily declare new test suites in Java projects
 - Support for Java 17
 - Support for Scala 3

For more details see https://docs.gradle.org/7.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/circleci/project/node_modules/react-native-reanimated/android/react-native-reanimated-68-jsc.aar
Checking the license for package Android SDK Platform 31 in /opt/android/sdk/licenses
License for package Android SDK Platform 31 accepted.
Preparing "Install Android SDK Platform 31 (revision: 1)".
"Install Android SDK Platform 31 (revision: 1)" ready.
Installing Android SDK Platform 31 in /opt/android/sdk/platforms/android-31
"Install Android SDK Platform 31 (revision: 1)" complete.
"Install Android SDK Platform 31 (revision: 1)" finished.

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-webview', ':segment_analytics-react-native', ':segment_sovran-react-native'

> Task :app:clean
> Task :react-native-app-auth:clean UP-TO-DATE
> Task :react-native-async-storage_async-storage:clean UP-TO-DATE
> Task :react-native-blob-util:clean UP-TO-DATE
> Task :react-native-community_art:clean UP-TO-DATE
> Task :react-native-community_geolocation:clean UP-TO-DATE
> Task :react-native-community_netinfo:clean UP-TO-DATE
> Task :react-native-device-info:clean UP-TO-DATE
> Task :react-native-exception-handler:clean UP-TO-DATE
> Task :react-native-gesture-handler:clean UP-TO-DATE
> Task :react-native-inappbrowser-reborn:clean UP-TO-DATE
> Task :react-native-mapbox-gl_maps:clean UP-TO-DATE
> Task :react-native-masked-view_masked-view:clean UP-TO-DATE
> Task :react-native-pdf:clean UP-TO-DATE
> Task :react-native-permissions:clean UP-TO-DATE
> Task :react-native-push-notification:clean UP-TO-DATE
> Task :react-native-safe-area-context:clean UP-TO-DATE
> Task :react-native-screens:clean UP-TO-DATE
> Task :react-native-share:clean UP-TO-DATE
> Task :react-native-splash-screen:clean UP-TO-DATE
> Task :react-native-svg:clean
> Task :react-native-vector-icons:clean UP-TO-DATE
> Task :react-native-version-check:clean UP-TO-DATE
> Task :react-native-view-pdf:clean UP-TO-DATE
> Task :react-native-webview:clean UP-TO-DATE
> Task :realm:clean UP-TO-DATE
> Task :segment_analytics-react-native:clean UP-TO-DATE
> Task :segment_sovran-react-native:clean UP-TO-DATE
> Task :sentry_react-native:clean UP-TO-DATE

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1m 20s
29 actionable tasks: 2 executed, 27 up-to-date
Jetifier found 1528 file(s) to forward-jetify. Using 36 workers...

> Configure project :react-native-reanimated
AAR for react-native-reanimated has been found
/home/circleci/project/node_modules/react-native-reanimated/android/react-native-reanimated-68-jsc.aar

The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build. 
This might happen in subprojects that apply the Kotlin plugins with the Gradle 'plugins { ... }' DSL if they specify explicit versions, even if the versions are equal.
Please add the Kotlin plugin to the common parent project or the root project, then remove the versions in the subprojects.
If the parent project does not need the plugin, add 'apply false' to the plugin line.
See: https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl
The Kotlin plugin was loaded in the following projects: ':react-native-webview', ':segment_analytics-react-native', ':segment_sovran-react-native'

> Task :app:generatePackageList
> Task :app:preBuild
> Task :app:preStageDebugBuild
> Task :react-native-app-auth:preBuild UP-TO-DATE
> Task :react-native-app-auth:preDebugBuild UP-TO-DATE
> Task :react-native-app-auth:compileDebugAidl NO-SOURCE
> Task :react-native-async-storage_async-storage:preBuild UP-TO-DATE
> Task :react-native-async-storage_async-storage:preDebugBuild UP-TO-DATE
> Task :react-native-async-storage_async-storage:compileDebugAidl NO-SOURCE
> Task :react-native-blob-util:preBuild UP-TO-DATE
> Task :react-native-blob-util:preDebugBuild UP-TO-DATE
> Task :react-native-blob-util:compileDebugAidl NO-SOURCE
> Task :react-native-community_art:preBuild UP-TO-DATE
> Task :react-native-community_art:preDebugBuild UP-TO-DATE
> Task :react-native-community_art:compileDebugAidl NO-SOURCE
> Task :react-native-community_geolocation:preBuild UP-TO-DATE
> Task :react-native-community_geolocation:preDebugBuild UP-TO-DATE
> Task :react-native-community_geolocation:compileDebugAidl NO-SOURCE
> Task :react-native-community_netinfo:preBuild UP-TO-DATE
> Task :react-native-community_netinfo:preDebugBuild UP-TO-DATE
> Task :react-native-community_netinfo:compileDebugAidl NO-SOURCE
> Task :react-native-device-info:preBuild UP-TO-DATE
> Task :react-native-device-info:preDebugBuild UP-TO-DATE
> Task :react-native-device-info:compileDebugAidl NO-SOURCE
> Task :react-native-exception-handler:preBuild UP-TO-DATE
> Task :react-native-exception-handler:preDebugBuild UP-TO-DATE
> Task :react-native-exception-handler:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preDebugBuild UP-TO-DATE
> Task :react-native-inappbrowser-reborn:preBuild UP-TO-DATE
> Task :react-native-inappbrowser-reborn:preDebugBuild UP-TO-DATE
> Task :react-native-inappbrowser-reborn:compileDebugAidl NO-SOURCE
> Task :react-native-mapbox-gl_maps:preBuild UP-TO-DATE
> Task :react-native-mapbox-gl_maps:preDebugBuild UP-TO-DATE
> Task :react-native-mapbox-gl_maps:compileDebugAidl NO-SOURCE
> Task :react-native-masked-view_masked-view:preBuild UP-TO-DATE
> Task :react-native-masked-view_masked-view:preDebugBuild UP-TO-DATE
> Task :react-native-masked-view_masked-view:compileDebugAidl NO-SOURCE
> Task :react-native-pdf:preBuild UP-TO-DATE
> Task :react-native-pdf:preDebugBuild UP-TO-DATE
> Task :react-native-pdf:compileDebugAidl NO-SOURCE
> Task :react-native-permissions:preBuild UP-TO-DATE
> Task :react-native-permissions:preDebugBuild UP-TO-DATE
> Task :react-native-permissions:compileDebugAidl NO-SOURCE
> Task :react-native-push-notification:preBuild UP-TO-DATE
> Task :react-native-push-notification:preDebugBuild UP-TO-DATE
> Task :react-native-push-notification:compileDebugAidl NO-SOURCE
> Task :react-native-safe-area-context:preBuild UP-TO-DATE
> Task :react-native-safe-area-context:preDebugBuild UP-TO-DATE
> Task :react-native-safe-area-context:compileDebugAidl NO-SOURCE
> Task :react-native-screens:preBuild UP-TO-DATE
> Task :react-native-screens:preDebugBuild UP-TO-DATE
> Task :react-native-screens:compileDebugAidl NO-SOURCE
> Task :react-native-share:preBuild UP-TO-DATE
> Task :react-native-share:preDebugBuild UP-TO-DATE
> Task :react-native-share:compileDebugAidl NO-SOURCE
> Task :react-native-splash-screen:preBuild UP-TO-DATE
> Task :react-native-splash-screen:preDebugBuild UP-TO-DATE
> Task :react-native-splash-screen:compileDebugAidl NO-SOURCE
> Task :react-native-svg:preBuild UP-TO-DATE
> Task :react-native-svg:preDebugBuild UP-TO-DATE
> Task :react-native-svg:compileDebugAidl NO-SOURCE
> Task :react-native-vector-icons:preBuild UP-TO-DATE
> Task :react-native-vector-icons:preDebugBuild UP-TO-DATE
> Task :react-native-vector-icons:compileDebugAidl NO-SOURCE
> Task :react-native-version-check:preBuild UP-TO-DATE
> Task :react-native-version-check:preDebugBuild UP-TO-DATE
> Task :react-native-version-check:compileDebugAidl NO-SOURCE
> Task :react-native-view-pdf:preBuild UP-TO-DATE
> Task :react-native-view-pdf:preDebugBuild UP-TO-DATE
> Task :react-native-view-pdf:compileDebugAidl NO-SOURCE
> Task :react-native-webview:preBuild UP-TO-DATE
> Task :react-native-webview:preDebugBuild UP-TO-DATE
> Task :react-native-webview:compileDebugAidl NO-SOURCE
> Task :realm:preBuild UP-TO-DATE
> Task :realm:preDebugBuild UP-TO-DATE
> Task :realm:compileDebugAidl NO-SOURCE
> Task :segment_analytics-react-native:preBuild UP-TO-DATE
> Task :segment_analytics-react-native:preDebugBuild UP-TO-DATE
> Task :segment_sovran-react-native:preBuild UP-TO-DATE
> Task :segment_sovran-react-native:preDebugBuild UP-TO-DATE
> Task :segment_sovran-react-native:compileDebugAidl NO-SOURCE
> Task :segment_analytics-react-native:compileDebugAidl NO-SOURCE
> Task :sentry_react-native:preBuild UP-TO-DATE
> Task :sentry_react-native:preDebugBuild UP-TO-DATE
> Task :sentry_react-native:compileDebugAidl NO-SOURCE
> Task :react-native-app-auth:packageDebugRenderscript NO-SOURCE
> Task :react-native-async-storage_async-storage:packageDebugRenderscript NO-SOURCE
> Task :react-native-blob-util:packageDebugRenderscript NO-SOURCE
> Task :react-native-community_art:packageDebugRenderscript NO-SOURCE
> Task :react-native-community_geolocation:packageDebugRenderscript NO-SOURCE
> Task :react-native-community_netinfo:packageDebugRenderscript NO-SOURCE
> Task :react-native-device-info:packageDebugRenderscript NO-SOURCE
> Task :react-native-exception-handler:packageDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :react-native-inappbrowser-reborn:packageDebugRenderscript NO-SOURCE
> Task :react-native-mapbox-gl_maps:packageDebugRenderscript NO-SOURCE
> Task :react-native-masked-view_masked-view:packageDebugRenderscript NO-SOURCE
> Task :react-native-pdf:packageDebugRenderscript NO-SOURCE
> Task :react-native-permissions:packageDebugRenderscript NO-SOURCE
> Task :react-native-push-notification:packageDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:packageDebugRenderscript NO-SOURCE
> Task :react-native-screens:packageDebugRenderscript NO-SOURCE
> Task :react-native-share:packageDebugRenderscript NO-SOURCE
> Task :react-native-splash-screen:packageDebugRenderscript NO-SOURCE
> Task :react-native-svg:packageDebugRenderscript NO-SOURCE
> Task :react-native-vector-icons:packageDebugRenderscript NO-SOURCE
> Task :react-native-version-check:packageDebugRenderscript NO-SOURCE
> Task :react-native-view-pdf:packageDebugRenderscript NO-SOURCE
> Task :react-native-webview:packageDebugRenderscript NO-SOURCE
> Task :realm:packageDebugRenderscript NO-SOURCE
> Task :segment_analytics-react-native:packageDebugRenderscript NO-SOURCE
> Task :segment_sovran-react-native:packageDebugRenderscript NO-SOURCE
> Task :sentry_react-native:packageDebugRenderscript NO-SOURCE
> Task :app:generateStageDebugBuildConfig
> Task :app:javaPreCompileStageDebug
> Task :react-native-app-auth:writeDebugAarMetadata
> Task :react-native-async-storage_async-storage:writeDebugAarMetadata
> Task :react-native-blob-util:writeDebugAarMetadata
> Task :react-native-community_art:writeDebugAarMetadata
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :app:compileStageDebugAidl NO-SOURCE
> Task :app:compileStageDebugRenderscript NO-SOURCE
> Task :react-native-community_geolocation:writeDebugAarMetadata
> Task :react-native-community_netinfo:writeDebugAarMetadata
> Task :react-native-device-info:writeDebugAarMetadata
> Task :react-native-exception-handler:writeDebugAarMetadata
> Task :react-native-gesture-handler:writeDebugAarMetadata
> Task :react-native-inappbrowser-reborn:writeDebugAarMetadata
> Task :react-native-mapbox-gl_maps:writeDebugAarMetadata
> Task :react-native-masked-view_masked-view:writeDebugAarMetadata
> Task :react-native-pdf:writeDebugAarMetadata
> Task :react-native-permissions:writeDebugAarMetadata
> Task :react-native-push-notification:writeDebugAarMetadata
> Task :react-native-safe-area-context:writeDebugAarMetadata
> Task :react-native-screens:writeDebugAarMetadata
> Task :react-native-share:writeDebugAarMetadata
> Task :react-native-splash-screen:writeDebugAarMetadata
> Task :react-native-svg:writeDebugAarMetadata
> Task :react-native-vector-icons:writeDebugAarMetadata
> Task :react-native-version-check:writeDebugAarMetadata
> Task :react-native-view-pdf:writeDebugAarMetadata
> Task :react-native-webview:writeDebugAarMetadata
> Task :realm:writeDebugAarMetadata
> Task :segment_analytics-react-native:writeDebugAarMetadata
> Task :segment_sovran-react-native:writeDebugAarMetadata
> Task :sentry_react-native:writeDebugAarMetadata
> Task :app:bundleStageDebugJsAndAssets SKIPPED
> Task :app:mergeStageDebugShaders
> Task :app:compileStageDebugShaders NO-SOURCE
> Task :app:generateStageDebugAssets UP-TO-DATE
> Task :react-native-app-auth:mergeDebugShaders
> Task :react-native-app-auth:compileDebugShaders NO-SOURCE
> Task :react-native-app-auth:generateDebugAssets UP-TO-DATE
> Task :react-native-app-auth:packageDebugAssets
> Task :react-native-async-storage_async-storage:mergeDebugShaders
> Task :react-native-async-storage_async-storage:compileDebugShaders NO-SOURCE
> Task :react-native-async-storage_async-storage:generateDebugAssets UP-TO-DATE
> Task :react-native-async-storage_async-storage:packageDebugAssets
> Task :react-native-blob-util:mergeDebugShaders
> Task :react-native-blob-util:compileDebugShaders NO-SOURCE
> Task :react-native-blob-util:generateDebugAssets UP-TO-DATE
> Task :react-native-blob-util:packageDebugAssets
> Task :react-native-community_art:mergeDebugShaders
> Task :react-native-community_art:compileDebugShaders NO-SOURCE
> Task :react-native-community_art:generateDebugAssets UP-TO-DATE
> Task :react-native-community_art:packageDebugAssets
> Task :react-native-community_geolocation:mergeDebugShaders
> Task :react-native-community_geolocation:compileDebugShaders NO-SOURCE
> Task :react-native-community_geolocation:generateDebugAssets UP-TO-DATE
> Task :react-native-community_geolocation:packageDebugAssets
> Task :react-native-community_netinfo:mergeDebugShaders
> Task :react-native-community_netinfo:compileDebugShaders NO-SOURCE
> Task :react-native-community_netinfo:generateDebugAssets UP-TO-DATE
> Task :react-native-community_netinfo:packageDebugAssets
> Task :react-native-device-info:mergeDebugShaders
> Task :react-native-device-info:compileDebugShaders NO-SOURCE
> Task :react-native-device-info:generateDebugAssets UP-TO-DATE
> Task :react-native-device-info:packageDebugAssets
> Task :react-native-exception-handler:mergeDebugShaders
> Task :react-native-exception-handler:compileDebugShaders NO-SOURCE
> Task :react-native-exception-handler:generateDebugAssets UP-TO-DATE
> Task :react-native-exception-handler:packageDebugAssets
> Task :react-native-gesture-handler:mergeDebugShaders
> Task :react-native-gesture-handler:compileDebugShaders NO-SOURCE
> Task :react-native-gesture-handler:generateDebugAssets UP-TO-DATE
> Task :react-native-gesture-handler:packageDebugAssets
> Task :react-native-inappbrowser-reborn:mergeDebugShaders
> Task :react-native-inappbrowser-reborn:compileDebugShaders NO-SOURCE
> Task :react-native-inappbrowser-reborn:generateDebugAssets UP-TO-DATE
> Task :react-native-inappbrowser-reborn:packageDebugAssets
> Task :react-native-mapbox-gl_maps:mergeDebugShaders
> Task :react-native-mapbox-gl_maps:compileDebugShaders NO-SOURCE
> Task :react-native-mapbox-gl_maps:generateDebugAssets UP-TO-DATE
> Task :react-native-mapbox-gl_maps:packageDebugAssets
> Task :react-native-masked-view_masked-view:mergeDebugShaders
> Task :react-native-masked-view_masked-view:compileDebugShaders NO-SOURCE
> Task :react-native-masked-view_masked-view:generateDebugAssets UP-TO-DATE
> Task :react-native-masked-view_masked-view:packageDebugAssets
> Task :react-native-pdf:mergeDebugShaders
> Task :react-native-pdf:compileDebugShaders NO-SOURCE
> Task :react-native-pdf:generateDebugAssets UP-TO-DATE
> Task :react-native-pdf:packageDebugAssets
> Task :react-native-permissions:mergeDebugShaders
> Task :react-native-permissions:compileDebugShaders NO-SOURCE
> Task :react-native-permissions:generateDebugAssets UP-TO-DATE
> Task :react-native-permissions:packageDebugAssets
> Task :react-native-push-notification:mergeDebugShaders
> Task :react-native-push-notification:compileDebugShaders NO-SOURCE
> Task :react-native-push-notification:generateDebugAssets UP-TO-DATE
> Task :react-native-push-notification:packageDebugAssets
> Task :react-native-safe-area-context:mergeDebugShaders
> Task :react-native-safe-area-context:compileDebugShaders NO-SOURCE
> Task :react-native-safe-area-context:generateDebugAssets UP-TO-DATE
> Task :react-native-safe-area-context:packageDebugAssets
> Task :react-native-screens:mergeDebugShaders
> Task :react-native-screens:compileDebugShaders NO-SOURCE
> Task :react-native-screens:generateDebugAssets UP-TO-DATE
> Task :react-native-screens:packageDebugAssets
> Task :react-native-share:mergeDebugShaders
> Task :react-native-share:compileDebugShaders NO-SOURCE
> Task :react-native-share:generateDebugAssets UP-TO-DATE
> Task :react-native-share:packageDebugAssets
> Task :react-native-splash-screen:mergeDebugShaders
> Task :react-native-splash-screen:compileDebugShaders NO-SOURCE
> Task :react-native-splash-screen:generateDebugAssets UP-TO-DATE
> Task :react-native-splash-screen:packageDebugAssets
> Task :react-native-svg:mergeDebugShaders
> Task :react-native-svg:compileDebugShaders NO-SOURCE
> Task :react-native-svg:generateDebugAssets UP-TO-DATE
> Task :react-native-svg:packageDebugAssets
> Task :react-native-vector-icons:mergeDebugShaders
> Task :react-native-vector-icons:compileDebugShaders NO-SOURCE
> Task :react-native-vector-icons:generateDebugAssets UP-TO-DATE
> Task :react-native-vector-icons:packageDebugAssets
> Task :react-native-version-check:mergeDebugShaders
> Task :react-native-version-check:compileDebugShaders NO-SOURCE
> Task :react-native-version-check:generateDebugAssets UP-TO-DATE
> Task :react-native-version-check:packageDebugAssets
> Task :react-native-view-pdf:mergeDebugShaders
> Task :react-native-view-pdf:compileDebugShaders NO-SOURCE
> Task :react-native-view-pdf:generateDebugAssets UP-TO-DATE
> Task :react-native-view-pdf:packageDebugAssets
> Task :react-native-webview:mergeDebugShaders
> Task :react-native-webview:compileDebugShaders NO-SOURCE
> Task :react-native-webview:generateDebugAssets UP-TO-DATE
> Task :react-native-webview:packageDebugAssets
> Task :realm:mergeDebugShaders
> Task :realm:compileDebugShaders NO-SOURCE
> Task :realm:generateDebugAssets UP-TO-DATE
> Task :realm:packageDebugAssets
> Task :segment_analytics-react-native:mergeDebugShaders
> Task :segment_analytics-react-native:compileDebugShaders NO-SOURCE
> Task :segment_analytics-react-native:generateDebugAssets UP-TO-DATE
> Task :segment_analytics-react-native:packageDebugAssets
> Task :segment_sovran-react-native:mergeDebugShaders
> Task :segment_sovran-react-native:compileDebugShaders NO-SOURCE
> Task :segment_sovran-react-native:generateDebugAssets UP-TO-DATE
> Task :segment_sovran-react-native:packageDebugAssets
> Task :sentry_react-native:mergeDebugShaders
> Task :sentry_react-native:compileDebugShaders NO-SOURCE
> Task :sentry_react-native:generateDebugAssets UP-TO-DATE
> Task :sentry_react-native:packageDebugAssets
> Task :app:mergeStageDebugAssets
> Task :app:copyStageDebugBundledJs SKIPPED
> Task :app:easylauncherStageDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:easylauncherStageDebug'.
> java.lang.reflect.InvocationTargetException

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 19s
90 actionable tasks: 90 executed

Exited with code exit status 1
CircleCI received exit code 1`

**Comment by mateuszkwiecinski** [comment] 2022-05-20 13:06
Is your build environment dockerized? Maybe you hit this issue: https://github.com/usefulness/easylauncher-gradle-plugin/issues/201? 
Can you share full stacktrace, by running the gradle command with `--stacktrace` argument? You pasted full console log, but it doesn't have all the precious information about the source of the error

**Comment by mahipalsingh-syt** [comment] 2022-05-20 13:22
Yes i'm using circleci. @mateuszkwiecinski

**Comment by mateuszkwiecinski** [comment] 2022-05-20 13:59
Cool! So this means this is a duplicate of #201. Feel free to share the details I requested above, in case your issue is any different :)

**Closed by mateuszkwiecinski** 2022-05-20 13:59 UTC

**Comment by mahipalsingh-syt** [comment] 2022-08-25 04:06
this works for me @mateuszkwiecinski 

https://github.com/usefulness/easylauncher-gradle-plugin/issues/201#issuecomment-1195274416
